image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install -y -qq lftp

deploy_uat:
  stage: deploy
  environment: Uat
  only:
    - uat
  script:
    #    - rm ./package-lock.json
    - npm install
    - npm run env
    - ./node_modules/@angular/cli/bin/ng build --progress false --configuration=production
    - ls
    - 'echo "user: " $FTP_USERNAME'
    - 'echo "password: " $FTP_PASSWORD'
    - lftp -e "set ssl:verify-certificate no; set ftp:ssl-allow no; open ftp://ftp.samyahmed.com:21; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete dist/ uat/; bye"

deploy_production:
  stage: deploy
  environment: Production
  only:
    - test
  script:
    #    - rm ./package-lock.json
    - npm install
    - npm run env
    - ./node_modules/@angular/cli/bin/ng build --progress false --configuration=production
    - ls
    - 'echo "user: " $FTP_USERNAME'
    - 'echo "password: " $FTP_PASSWORD'
    - lftp -e "set ssl:verify-certificate no; set ftp:ssl-allow no; open ftp://ftp.samyahmed.com:21; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete dist/ test/; bye"
