image: 'node:10.15.3'
clone:
  depth: full
pipelines:
  branches:
    test:
      - step:
          name: 'Build Production'
          deployment: production
          caches:
            - node
          script:
            - 'npm install -g @angular/cli'
            - 'npm install'
            - './node_modules/@angular/cli/bin/ng build --progress false --configuration=production'
            - 'echo "Let''s go in to our dist/ and initialize there with git"'
            - 'cd dist/'
            - 'git config --global user.email "samyahmedibrahim@gmail.com"'
            - 'git config --global user.name "Samy Ahmed"'
            - 'git init'
            - 'git add -A && git commit -m "base url updated for prod deployment"'
            - 'git clone https://github.com/git-ftp/git-ftp.git'
            - 'cd git-ftp'
            - 'git checkout 1.3.4'
            - 'make install'
            - 'echo "Done with installation of git-ftp"'
            - 'cd ../'
            - 'rm -rf git-ftp'
            - 'git config git-ftp.url "ftp://ftp.samyahmed.com:21/test"'
            - 'git config git-ftp.user $FTP_USERNAME'
            - 'git config git-ftp.password $FTP_PASSWORD'
            - 'git ftp push --auto-init'
    uat:
      - step: null
        name: 'Build Uat'
        deployment: uat
        caches:
          - node
        script:
          - 'npm install -g @angular/cli'
          - 'npm install'
          - './node_modules/@angular/cli/bin/ng build --progress false --configuration=production'
          - 'echo "Let''s go in to our dist/ and initialize there with git"'
          - 'cd dist/'
          - 'git config --global user.email "samyahmedibrahim@gmail.com"'
          - 'git config --global user.name "Samy Ahmed"'
          - 'git init'
          - 'git add -A && git commit -m "base url updated for prod deployment"'
          - 'git clone https://github.com/git-ftp/git-ftp.git'
          - 'cd git-ftp'
          - 'git checkout 1.3.4'
          - 'make install'
          - 'echo "Done with installation of git-ftp"'
          - 'cd ../'
          - 'rm -rf git-ftp'
          - 'git config git-ftp.url "ftp://ftp.samyahmed.com:21/uat"'
          - 'git config git-ftp.user $FTP_USERNAME'
          - 'git config git-ftp.password $FTP_PASSWORD'
          - 'git ftp push --auto-init'
